steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t', 'asia.gcr.io/$PROJECT_ID/sandbox',
        '-f', 'Dockerfile',
        '.'
    ]
images: ['asia.gcr.io/$PROJECT_ID/sandbox']
